"""Add model MatchCalendar

Revision ID: 160ea8a1f877
Revises: e2d75e820dec
Create Date: 2025-05-08 10:19:40.133169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '160ea8a1f877'
down_revision = 'e2d75e820dec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_calendar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('players', sa.String(length=200), nullable=False),
    sa.Column('time', sa.String(length=5), nullable=False),
    sa.Column('court', sa.String(length=50), nullable=False),
    sa.Column('match_date', sa.DateTime(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_calendar')
    # ### end Alembic commands ###
